### ISSUE TITLE
getPagesByTerm limit, sort, dir, empty doesn't work

### ISSUE THREAD

**Issue by Pejic88** [craftsmancoding/taxonomies#13]
1) I tried to limit, sort by publishedon and change order to DESC but it's not working, this snippet always gives all of the pages.

2) I set a message with :empty to be displayed when there is no pages for that term and there is no message when it has to be showed

This is my code:
[[!getPagesByTerm:empty=`[[$blog_no_posts]]`?
  &outerTpl=``
  &innerTpl=`blog_post_view_category`
  &limit=`1`
  &sort=`Page.publishedon`
  &dir=`DESC`
  &debug=`1`
]]

**Comment by dadaniels** [comment]
@Pejic88 
I took a look on your issue and added 2 more paramters on getPagesByterm
1. On your first concern, I added limit param. With regards to sorting, you're writing the snippet call incorrectly arguments must have "`DESC`" like &dir=`DESC`, same with other parameters.
2. That call wont work, so instead I added a &noResultTpl param. YOu can supply this with a simple text, a chunk name, a chunk call or an inline html. please check out the documentation for this.

Correct call:
[[!getPagesByTerm? &outerTpl=`blog_post_chunk_here` &innerTpl=`blog_post_view_category` &limit=`1` &sort=`Page.publishedon` &dir=`DESC` &debug=1`&noresultTpl=`blog_no_posts`]]

**Comment by fireproofsocks** [comment]
The problem as originally reported seems to be that a term_id was not included (?).  Remember: the `empty` output filter only works when there is no output (not when there _should_ have been no output), so if you were getting output (intended or not), then the `empty` filter would never have been applied.  

The omission of the "noResultTpl" or similar arguments is intentional: it's not needed.  The use of the `empty` output filter already provides a way to show conditional output.  E.g. the following snippet syntax is correct:

````
[[!MySnippet:empty=`This snippet returned nothing.`? &param=`x`]]
````

I am removing the `&noResultTpl` parameter prior to releasing this as a new version.  I'm also renaming the inputs to better reflect what they do: `sort` and `dir`

I added tests for this as well.  This will go out in the next release.

b10c25b..c342e20  master -> master
