### ISSUE TITLE
TagCloud Request - Sort by Count

### ISSUE THREAD

**Issue by BearsFan** [craftsmancoding/taxonomies#14]
feature request - TagCLoud, sort by Count, useful for showing most popular tags obviously

**Comment by dadaniels** [comment]
@BearsFan 
I added 2 more params to grant your request. &sortByCount which defaults to 0 which means dont sort by count and &sortCountDir default to DESC. If you want to sort tags by count set sortByCount  to 1.

**Comment by fireproofsocks** [comment]
A couple things changed before this is complete:

1. The new parameters were documented in the Snippet's comments (not just on the wiki)
2. The parameters were named more generally: `sort` and `dir` because they don't apply just to the "count" sorting; they can be applied to any valid field.
3. I replaced the hard-coded table names: `modx_site_content` contains a variable `$table_prefix`.  Same with the `tax_page_terms`

This will be released in the next update.
